### ISSUE TITLE
Issues when using first-party plugins

### ISSUE THREAD

**Issue by furioursus** [elliotlewis/Redactor-Extras#1]
I’m attempting to use the Redactor II [Properties Plugin](https://imperavi.com/redactor/plugins/properties/) with this plugin, but it seems that it’s trying to load the JavaScript _right_ before Redactor is getting called. Should I be stripping anything from the plugin or massaging it to make it work in this instance?

It's failing at line 3 of the properties.js plugin, `$.Redactor.prototype.properties = function()` which is returning "TypeError: undefined is not an object (evaluating '$.Redactor.prototype')" for the above mentioned reason.

**Comment by elliotlewis** [comment]
Sorry @onebrightlight, I didn't get emailed about this issue.

Checkout the included 'plugins' in this plugin and the ones that ship with Craft. Craft loads redactor in a slightly different way so you can't just copy and use code from Redactors site, but it's quite simple.

`craft/app/resources/lib/redactor/`

I'll add Redactors Properties plugin in the next week as choice, in the meantime you can format your code like this:

```
if (!RedactorPlugins) var RedactorPlugins = {};
    RedactorPlugins.properties = function()
```

NOT

```
(function($)
{
$.Redactor.prototype.properties = function()
{
```

**Comment by elliotlewis** [comment]
Properties plugin added as a first-class option to 'Redactor Extras' plugin.
